# Generated by Django 3.1.7 on 2021-03-15 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Рубрика',
                'verbose_name_plural': 'Рубрики',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'Нахуй пшёл'}, max_length=24, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('sName', models.CharField(db_index=True, error_messages={'invalid': 'Нахуй пшёл'}, max_length=24, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлен')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта')),
                ('pNumber', models.CharField(max_length=24, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Товар')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('rubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engboard.rubric', verbose_name='Рубрика')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Apprentice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'invalid': 'Нахуй пшёл'}, max_length=24, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Имя')),
                ('sName', models.CharField(db_index=True, error_messages={'invalid': 'Нахуй пшёл'}, max_length=24, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Фамилия')),
                ('pNumber', models.CharField(db_index=True, max_length=24, verbose_name='Номер телефона')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Добавлен')),
                ('email', models.EmailField(max_length=254, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Электронная почта')),
                ('lvl', models.CharField(max_length=24, null=True, verbose_name='Уровень языка')),
                ('active', models.BooleanField(null=True, verbose_name='Активен')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='engboard.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['name'],
            },
        ),
    ]
